# Generated by Django 4.2.2 on 2023-07-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_rename_body_comments_content_remove_comments_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
